//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnonPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa aplikacji: {0}
        ///Wersja: {1}
        ///Firma: {2}
        ///{3}
        ///
        ///Opis: {4}
        ///
        ///Licencje i komponenty:
        ///- iText 9 (AGPL-3.0)
        ///- PDFiumSharp / PDFium
        ///- Newtonsoft.Json (MIT)
        ///- BouncyCastle (MIT)
        ///- TesseractOCR (.NET) (Apache-2.0)
        ///
        ///Kod źródłowy dostępny zgodnie z AGPL-3.0 (zobacz plik LICENSE).
        ///Repozytorium: https://github.com/umszczecin/AnonPDF.
        /// </summary>
        internal static string About_Message {
            get {
                return ResourceManager.GetString("About_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj chociaż jeden numer strony lub krok podziału!.
        /// </summary>
        internal static string Delete_Err_NoData {
            get {
                return ResourceManager.GetString("Delete_Err_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona początkowa nie może być większa od końcowej..
        /// </summary>
        internal static string Delete_Err_StartGreater {
            get {
                return ResourceManager.GetString("Delete_Err_StartGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona końcowa:.
        /// </summary>
        internal static string Delete_Label_End {
            get {
                return ResourceManager.GetString("Delete_Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona początkowa:.
        /// </summary>
        internal static string Delete_Label_Start {
            get {
                return ResourceManager.GetString("Delete_Label_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krok:.
        /// </summary>
        internal static string Delete_Label_Step {
            get {
                return ResourceManager.GetString("Delete_Label_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz do usunięcia.
        /// </summary>
        internal static string Delete_Radio_Apply {
            get {
                return ResourceManager.GetString("Delete_Radio_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj wybór.
        /// </summary>
        internal static string Delete_Radio_Cancel {
            get {
                return ResourceManager.GetString("Delete_Radio_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zakres stron.
        /// </summary>
        internal static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki PAP (*.pap)|*.pap.
        /// </summary>
        internal static string Dialog_Filter_PAP {
            get {
                return ResourceManager.GetString("Dialog_Filter_PAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki PDF (*.pdf)|*.pdf.
        /// </summary>
        internal static string Dialog_Filter_PDF {
            get {
                return ResourceManager.GetString("Dialog_Filter_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik projektu AnonPDF.
        /// </summary>
        internal static string Dialog_Title_OpenPap {
            get {
                return ResourceManager.GetString("Dialog_Title_OpenPap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik PDF.
        /// </summary>
        internal static string Dialog_Title_OpenPdf {
            get {
                return ResourceManager.GetString("Dialog_Title_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę pliku projektu AnonPDF.
        /// </summary>
        internal static string Dialog_Title_SavePap {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz plik PDF pod inną nazwą niż bieżąca.
        /// </summary>
        internal static string Dialog_Title_SavePdfAs {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePdfAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Środek.
        /// </summary>
        internal static string EditText_AlignCenter {
            get {
                return ResourceManager.GetString("EditText_AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lewo.
        /// </summary>
        internal static string EditText_AlignLeft {
            get {
                return ResourceManager.GetString("EditText_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prawo.
        /// </summary>
        internal static string EditText_AlignRight {
            get {
                return ResourceManager.GetString("EditText_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz kolor.
        /// </summary>
        internal static string EditText_ButtonColor {
            get {
                return ResourceManager.GetString("EditText_ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz czcionkę.
        /// </summary>
        internal static string EditText_ButtonFont {
            get {
                return ResourceManager.GetString("EditText_ButtonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź jakiś tekst..
        /// </summary>
        internal static string EditText_EmptyError {
            get {
                return ResourceManager.GetString("EditText_EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyrównanie.
        /// </summary>
        internal static string EditText_GroupAlignment {
            get {
                return ResourceManager.GetString("EditText_GroupAlignment", resourceCulture);
            }
        }
        
        internal static string EditText_GroupRotation {
            get {
                return ResourceManager.GetString("EditText_GroupRotation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kąt (°):.
        /// </summary>
        internal static string EditText_RotationLabel {
            get {
                return ResourceManager.GetString("EditText_RotationLabel", resourceCulture);
            }
        }
        
        internal static string EditText_GroupSymbols {
            get {
                return ResourceManager.GetString("EditText_GroupSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź tekst:.
        /// </summary>
        internal static string EditText_LabelText {
            get {
                return ResourceManager.GetString("EditText_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj napis.
        /// </summary>
        internal static string EditText_Title {
            get {
                return ResourceManager.GetString("EditText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zapisać — wszystkie strony oznaczone do usunięcia..
        /// </summary>
        internal static string Err_AllPagesMarked {
            get {
                return ResourceManager.GetString("Err_AllPagesMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tego pliku PDF nie można zanonimizować!.
        /// </summary>
        internal static string Err_CannotAnonymizePdf {
            get {
                return ResourceManager.GetString("Err_CannotAnonymizePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznaczenie poza bitmapą lub zerowe: {0}.
        /// </summary>
        internal static string Err_Crop_OutsideBitmap {
            get {
                return ResourceManager.GetString("Err_Crop_OutsideBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne hasło – spróbuj ponownie..
        /// </summary>
        internal static string Err_IncorrectPassword {
            get {
                return ResourceManager.GetString("Err_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj poprawny numer strony..
        /// </summary>
        internal static string Err_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Err_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy numer strony: &apos;{0}&apos;..
        /// </summary>
        internal static string Err_InvalidPageNumberValue {
            get {
                return ResourceManager.GetString("Err_InvalidPageNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten plik PDF jest nieprawidłowy.
        ///
        ///Sprawdź czy możesz go otworzyć w innej aplikacji..
        /// </summary>
        internal static string Err_InvalidPdfFile {
            get {
                return ResourceManager.GetString("Err_InvalidPdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten format projektu jest nieprawidłowy.
        ///
        ///Skontaktuj się z autorem aplikacji..
        /// </summary>
        internal static string Err_InvalidProjectFormat {
            get {
                return ResourceManager.GetString("Err_InvalidProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas wczytywania ostatnich plików: {0}.
        /// </summary>
        internal static string Err_LoadRecentFiles {
            get {
                return ResourceManager.GetString("Err_LoadRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak skojarzonej aplikacji PDF: {0}.
        /// </summary>
        internal static string Err_NoAssociatedPdfApp {
            get {
                return ResourceManager.GetString("Err_NoAssociatedPdfApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd OCR: {0}.
        /// </summary>
        internal static string Err_OCR {
            get {
                return ResourceManager.GetString("Err_OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zapisać pliku PDF. Plik wyjściowy jest obecnie używany..
        /// </summary>
        internal static string Err_OutputInUse {
            get {
                return ResourceManager.GetString("Err_OutputInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas zapisywania: {0}.
        /// </summary>
        internal static string Err_Save {
            get {
                return ResourceManager.GetString("Err_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz właściwy plik projektu..
        /// </summary>
        internal static string Err_SelectValidProjectFile {
            get {
                return ResourceManager.GetString("Err_SelectValidProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbyt mała liczba stron w dokumencie!.
        /// </summary>
        internal static string Err_TooFewPages {
            get {
                return ResourceManager.GetString("Err_TooFewPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieobsłużony błąd aplikacji:
        ///
        ///{0}
        ///
        ///Szczegóły zapisano w:
        ///{1}.
        /// </summary>
        internal static string Err_UnhandledException {
            get {
                return ResourceManager.GetString("Err_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj napis.
        /// </summary>
        internal static string Menu_AddText {
            get {
                return ResourceManager.GetString("Menu_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj do schowka.
        /// </summary>
        internal static string Menu_CopyToClipboard {
            get {
                return ResourceManager.GetString("Menu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń stronę.
        /// </summary>
        internal static string Menu_DeletePage {
            get {
                return ResourceManager.GetString("Menu_DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obróć stronę.
        /// </summary>
        internal static string Menu_RotatePage {
            get {
                return ResourceManager.GetString("Menu_RotatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport obiektów graficznych.
        /// </summary>
        internal static string Menu_ExportGraphics {
            get {
                return ResourceManager.GetString("Menu_ExportGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Plik.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;omoc.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikacji.
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrukcja.
        /// </summary>
        internal static string Menu_Help_Help {
            get {
                return ResourceManager.GetString("Menu_Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż licencję.
        /// </summary>
        internal static string Menu_Help_ShowLicense {
            get {
                return ResourceManager.GetString("Menu_Help_ShowLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenty osób trzecich.
        /// </summary>
        internal static string Menu_Help_ThirdParty {
            get {
                return ResourceManager.GetString("Menu_Help_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samouczek.
        /// </summary>
        internal static string Menu_Help_Tutorial {
            get {
                return ResourceManager.GetString("Menu_Help_Tutorial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tryb diagnostyczny.
        /// </summary>
        internal static string Menu_Help_DiagnosticMode {
            get {
                return ResourceManager.GetString("Menu_Help_DiagnosticMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomijaj ograniczenia PDF.
        /// </summary>
        internal static string Menu_IgnorePdfRestrictions {
            get {
                return ResourceManager.GetString("Menu_IgnorePdfRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        internal static string Menu_Language_English {
            get {
                return ResourceManager.GetString("Menu_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        internal static string Menu_Language_Polish {
            get {
                return ResourceManager.GetString("Menu_Language_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj języka systemu.
        /// </summary>
        internal static string Menu_Language_System {
            get {
                return ResourceManager.GetString("Menu_Language_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scal pliki PDF.
        /// </summary>
        internal static string Menu_MergePdf {
            get {
                return ResourceManager.GetString("Menu_MergePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz ostatni PDF i projekt.
        /// </summary>
        internal static string Menu_OpenLast {
            get {
                return ResourceManager.GetString("Menu_OpenLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz PDF.
        /// </summary>
        internal static string Menu_OpenPdf {
            get {
                return ResourceManager.GetString("Menu_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz projekt.
        /// </summary>
        internal static string Menu_OpenProject {
            get {
                return ResourceManager.GetString("Menu_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op&amp;cje.
        /// </summary>
        internal static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz PDF.
        /// </summary>
        internal static string Menu_SavePdf {
            get {
                return ResourceManager.GetString("Menu_SavePdf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wybierz podpisy do usunięcia.
        /// </summary>
        internal static string Menu_SelectSignaturesToRemove {
            get {
                return ResourceManager.GetString("Menu_SelectSignaturesToRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ostatnio otwierane pliki.
        /// </summary>
        internal static string Menu_RecentFiles {
            get {
                return ResourceManager.GetString("Menu_RecentFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brak.
        /// </summary>
        internal static string Menu_RecentFiles_Empty {
            get {
                return ResourceManager.GetString("Menu_RecentFiles_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zamknij dokument.
        /// </summary>
        internal static string Menu_CloseDocument {
            get {
                return ResourceManager.GetString("Menu_CloseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz projekt zaznaczeń.
        /// </summary>
        internal static string Menu_SaveProject {
            get {
                return ResourceManager.GetString("Menu_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz projekt zaznaczeń jako.
        /// </summary>
        internal static string Menu_SaveProjectAs {
            get {
                return ResourceManager.GetString("Menu_SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podziel plik PDF.
        /// </summary>
        internal static string Menu_SplitPdf {
            get {
                return ResourceManager.GetString("Menu_SplitPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj katalog....
        /// </summary>
        internal static string Merge_AddDirectory {
            get {
                return ResourceManager.GetString("Merge_AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj pliki....
        /// </summary>
        internal static string Merge_AddFiles {
            get {
                return ResourceManager.GetString("Merge_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string Merge_Cancel {
            get {
                return ResourceManager.GetString("Merge_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść listę.
        /// </summary>
        internal static string Merge_ClearList {
            get {
                return ResourceManager.GetString("Merge_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W dół.
        /// </summary>
        internal static string Merge_Down {
            get {
                return ResourceManager.GetString("Merge_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas scalania: {0}.
        /// </summary>
        internal static string Merge_Err_Merge {
            get {
                return ResourceManager.GetString("Merge_Err_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Merge_OK {
            get {
                return ResourceManager.GetString("Merge_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zaznaczone.
        /// </summary>
        internal static string Merge_RemoveSelected {
            get {
                return ResourceManager.GetString("Merge_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki zostały pomyślnie scalone..
        /// </summary>
        internal static string Merge_Success {
            get {
                return ResourceManager.GetString("Merge_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalanie plików PDF.
        /// </summary>
        internal static string Merge_Title {
            get {
                return ResourceManager.GetString("Merge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W górę.
        /// </summary>
        internal static string Merge_Up {
            get {
                return ResourceManager.GetString("Merge_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można załadować ostatnio używanych plików..
        /// </summary>
        internal static string Msg_CannotLoadRecentFiles {
            get {
                return ResourceManager.GetString("Msg_CannotLoadRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz zdefiniowane zaznaczenia w treści
        ///
        ///.
        /// </summary>
        internal static string Msg_Closing_UnsavedSelectionsPrefix {
            get {
                return ResourceManager.GetString("Msg_Closing_UnsavedSelectionsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć wszystkie zaznaczenia z dokumentu?.
        /// </summary>
        internal static string Msg_Confirm_ClearAllSelections {
            get {
                return ResourceManager.GetString("Msg_Confirm_ClearAllSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz zamknąć aplikację?.
        /// </summary>
        internal static string Msg_Confirm_CloseApp {
            get {
                return ResourceManager.GetString("Msg_Confirm_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć ten napis?.
        /// </summary>
        internal static string Msg_Confirm_DeleteTextAnnotation {
            get {
                return ResourceManager.GetString("Msg_Confirm_DeleteTextAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz niezapisane zmiany redakcyjne w dokumencie.
        ///
        ///Czy na pewno chcesz je utracić?.
        /// </summary>
        internal static string Msg_Confirm_DiscardUnsavedRedactions {
            get {
                return ResourceManager.GetString("Msg_Confirm_DiscardUnsavedRedactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga, opcja wyszukiwania nazwisk w treści może być czasochłonna
        ///
        ///oraz może nie zwracać poprawnych wyników.
        ///
        ///Czy chcesz kontynuować?.
        /// </summary>
        internal static string Msg_Confirm_NameSearchSlow {
            get {
                return ResourceManager.GetString("Msg_Confirm_NameSearchSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz otworzyć nowy plik PDF?
        ///
        ///Masz zdefiniowane i nie zapisane zaznaczenia w treści....
        /// </summary>
        internal static string Msg_Confirm_OpenNewWithUnsavedSelections {
            get {
                return ResourceManager.GetString("Msg_Confirm_OpenNewWithUnsavedSelections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz zamknąć dokument?
        ///
        ///Masz zdefiniowane i nie zapisane zaznaczenia w treści....
        /// </summary>
        internal static string Msg_Confirm_CloseWithUnsavedSelections {
            get {
                return ResourceManager.GetString("Msg_Confirm_CloseWithUnsavedSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest to nieobsługiwany typ pliku. Przeciągnij plik PDF lub plik .pap..
        /// </summary>
        internal static string Msg_DragDrop_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Msg_DragDrop_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport obiektów graficznych zakończony.
        ///
        ///Pliki zapisano w katalogu:
        ///{0}.
        /// </summary>
        internal static string Msg_ExportGraphics_Done {
            get {
                return ResourceManager.GetString("Msg_ExportGraphics_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista plików jest pusta..
        /// </summary>
        internal static string Msg_FileListEmpty {
            get {
                return ResourceManager.GetString("Msg_FileListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił problem z otwarciem pliku: {0}.
        /// </summary>
        internal static string Msg_FileOpenError {
            get {
                return ResourceManager.GetString("Msg_FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik pomocy PDF nie został znaleziony w folderze aplikacji..
        /// </summary>
        internal static string Msg_HelpNotFound {
            get {
                return ResourceManager.GetString("Msg_HelpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik licencji &quot;LICENSE&quot; nie został znaleziony w folderze aplikacji..
        /// </summary>
        internal static string Msg_LicenseNotFound {
            get {
                return ResourceManager.GetString("Msg_LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załadowano:
        ///PDF: {0}.
        /// </summary>
        internal static string Msg_LoadedPdf {
            get {
                return ResourceManager.GetString("Msg_LoadedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Projekt: {0}.
        /// </summary>
        internal static string Msg_LoadedProjectLine {
            get {
                return ResourceManager.GetString("Msg_LoadedProjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usługa umożliwiająca wyszukiwanie nazwisk jest obecnie niedostępna..
        /// </summary>
        internal static string Msg_NameSearchServiceUnavailable {
            get {
                return ResourceManager.GetString("Msg_NameSearchServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykryto nowszą wersję aplikacji Anon PDF. Do {0} będzie przeprowadzana aktualizacja aplikacji.
        ///
        ///Proszę zapisać wyniki swojej pracy i wyłączyć program.
        ///
        ///Automatyczne wyłączenie nastąpi za 5 minut..
        /// </summary>
        internal static string Msg_NewVersionDetectedMaintenance {
            get {
                return ResourceManager.GetString("Msg_NewVersionDetectedMaintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dostępna jest nowsza wersja {0} (data aktualizacji: {1})..
        /// </summary>
        internal static string Msg_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Msg_NewVersionAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zmiany:.
        /// </summary>
        internal static string Msg_NewVersionChangesHeader {
            get {
                return ResourceManager.GetString("Msg_NewVersionChangesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brak listy zmian..
        /// </summary>
        internal static string Msg_NewVersionNoChanges {
            get {
                return ResourceManager.GetString("Msg_NewVersionNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link do pobrania: {0}.
        /// </summary>
        internal static string Msg_NewVersionDownload {
            get {
                return ResourceManager.GetString("Msg_NewVersionDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zainstalowana wersja przekracza zakres wykupionych aktualizacji. Licencja na nowsze wersje nie została wykupiona.
        ///
        ///Aplikacja przechodzi w tryb DEMO..
        /// </summary>
        internal static string Msg_UpdateLicenseOutOfRange {
            get {
                return ResourceManager.GetString("Msg_UpdateLicenseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W dokumencie nie znaleziono poprawnych numerów PESEL, KW i innych identyfikatorów..
        /// </summary>
        internal static string Msg_NoIdentifiersFound {
            get {
                return ResourceManager.GetString("Msg_NoIdentifiersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano hasła – otwarcie anulowane..
        /// </summary>
        internal static string Msg_NoPasswordOpenCancelled {
            get {
                return ResourceManager.GetString("Msg_NoPasswordOpenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na bieżącej stronie nie znaleziono wyników wyszukiwania..
        /// </summary>
        internal static string Msg_NoSearchResultsOnPage {
            get {
                return ResourceManager.GetString("Msg_NoSearchResultsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zaznaczeń na bieżącej stronie..
        /// </summary>
        internal static string Msg_NoSelectionsOnPage {
            get {
                return ResourceManager.GetString("Msg_NoSelectionsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się pobrać tekstu z żadnego zaznaczenia..
        /// </summary>
        internal static string Msg_NoTextFromSelections {
            get {
                return ResourceManager.GetString("Msg_NoTextFromSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik z informacjami o komponentach &quot;THIRD-PARTY-NOTICES.md&quot; nie został znaleziony w folderze aplikacji..
        /// </summary>
        internal static string Msg_NoticesNotFound {
            get {
                return ResourceManager.GetString("Msg_NoticesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił problem z otwarciem pliku PDF: {0}.
        /// </summary>
        internal static string Msg_OpenPdfError {
            get {
                return ResourceManager.GetString("Msg_OpenPdfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz najpierw plik PDF..
        /// </summary>
        internal static string Msg_OpenPdfFirst {
            get {
                return ResourceManager.GetString("Msg_OpenPdfFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź zapisany dokument PDF na podglądzie..
        /// </summary>
        internal static string Msg_PreviewSavedPdf {
            get {
                return ResourceManager.GetString("Msg_PreviewSavedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano bieżący stan prac nad projektem
        ///pod wybraną nazwą..
        /// </summary>
        internal static string Msg_ProjectSaved {
            get {
                return ResourceManager.GetString("Msg_ProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono &quot;{0}&quot;..
        /// </summary>
        internal static string Msg_SearchNotFound {
            get {
                return ResourceManager.GetString("Msg_SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualnie do {0} jest przeprowadzana aktualizacja aplikacji Anon PDF..
        /// </summary>
        internal static string Msg_ServiceUpdateInProgress {
            get {
                return ResourceManager.GetString("Msg_ServiceUpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja została zamknięta z przyczyn serwisowych. Czy chcesz przywrócić ostatnią sesję?.
        /// </summary>
        internal static string Msg_MaintenanceRecoveryPrompt {
            get {
                return ResourceManager.GetString("Msg_MaintenanceRecoveryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłączenie za {0}.
        /// </summary>
        internal static string Msg_MaintenanceCountdown {
            get {
                return ResourceManager.GetString("Msg_MaintenanceCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} możliwość zmiany pozycji tekstu..
        /// </summary>
        internal static string Msg_TextPositionInfo {
            get {
                return ResourceManager.GetString("Msg_TextPositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teksty z zaznaczeń zostały skopiowane do schowka..
        /// </summary>
        internal static string Msg_TextsCopiedToClipboard {
            get {
                return ResourceManager.GetString("Msg_TextsCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        internal static string PwdPrompt_Label_Password {
            get {
                return ResourceManager.GetString("PwdPrompt_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możesz zmienić lub usunąć hasło PDF.
        /// </summary>
        internal static string PwdPrompt_Title_CanChangeRemove {
            get {
                return ResourceManager.GetString("PwdPrompt_Title_CanChangeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj hasło PDF.
        /// </summary>
        internal static string PwdPrompt_Title_Enter {
            get {
                return ResourceManager.GetString("PwdPrompt_Title_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Signatures_Report_Field_SignDate {
            get {
                return ResourceManager.GetString("Signatures_Report_Field_SignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sygnatariusz.
        /// </summary>
        internal static string Signatures_Report_Field_SignerName {
            get {
                return ResourceManager.GetString("Signatures_Report_Field_SignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        internal static string Signatures_Report_Field_SignerTitle {
            get {
                return ResourceManager.GetString("Signatures_Report_Field_SignerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista podpisów kwalifikowanych w oryginalnym dokumencie (przed anonimizacją):.
        /// </summary>
        internal static string Signatures_Report_Title {
            get {
                return ResourceManager.GetString("Signatures_Report_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wybierz podpisy do usunięcia.
        /// </summary>
        internal static string Signatures_Select_Title {
            get {
                return ResourceManager.GetString("Signatures_Select_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Podpisujący.
        /// </summary>
        internal static string Signatures_Select_Column_Name {
            get {
                return ResourceManager.GetString("Signatures_Select_Column_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stanowisko.
        /// </summary>
        internal static string Signatures_Select_Column_Title {
            get {
                return ResourceManager.GetString("Signatures_Select_Column_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Signatures_Select_Column_Date {
            get {
                return ResourceManager.GetString("Signatures_Select_Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj....
        /// </summary>
        internal static string Split_Browse {
            get {
                return ResourceManager.GetString("Split_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik PDF.
        /// </summary>
        internal static string Split_Dlg_Title {
            get {
                return ResourceManager.GetString("Split_Dlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd przy odczycie pliku PDF:\n{0}.
        /// </summary>
        internal static string Split_Err_ReadFile {
            get {
                return ResourceManager.GetString("Split_Err_ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wybrać istniejący plik PDF..
        /// </summary>
        internal static string Split_Err_SelectFile {
            get {
                return ResourceManager.GetString("Split_Err_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik PDF:.
        /// </summary>
        internal static string Split_FileLabel {
            get {
                return ResourceManager.GetString("Split_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba stron: {0}.
        /// </summary>
        internal static string Split_PageCountLabel {
            get {
                return ResourceManager.GetString("Split_PageCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba stron: ?.
        /// </summary>
        internal static string Split_PageCountUnknown {
            get {
                return ResourceManager.GetString("Split_PageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj numery stron do podziału (oddzielone przecinkami):.
        /// </summary>
        internal static string Split_PagesLabel {
            get {
                return ResourceManager.GetString("Split_PagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj krok podziału:.
        /// </summary>
        internal static string Split_StepLabel {
            get {
                return ResourceManager.GetString("Split_StepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument PDF został podzielony..
        /// </summary>
        internal static string Split_Success {
            get {
                return ResourceManager.GetString("Split_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podział dokumentu PDF.
        /// </summary>
        internal static string Split_Title {
            get {
                return ResourceManager.GetString("Split_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie.
        /// </summary>
        internal static string Title_Confirmation {
            get {
                return ResourceManager.GetString("Title_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd krytyczny aplikacji.
        /// </summary>
        internal static string Title_CriticalAppError {
            get {
                return ResourceManager.GetString("Title_CriticalAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja.
        /// </summary>
        internal static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces.
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb box — zaznacz prostokątem..
        /// </summary>
        internal static string Tooltip_Box {
            get {
                return ResourceManager.GetString("Tooltip_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wszystkie zaznaczenia z dokumentu..
        /// </summary>
        internal static string Tooltip_ClearAll {
            get {
                return ResourceManager.GetString("Tooltip_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zaznaczenia z bieżącej strony..
        /// </summary>
        internal static string Tooltip_ClearPage {
            get {
                return ResourceManager.GetString("Tooltip_ClearPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza strona..
        /// </summary>
        internal static string Tooltip_FirstPage {
            get {
                return ResourceManager.GetString("Tooltip_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zapisie zaznaczenia będą wyróżnione kolorem..
        /// </summary>
        internal static string Tooltip_HighlightColor {
            get {
                return ResourceManager.GetString("Tooltip_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia strona..
        /// </summary>
        internal static string Tooltip_LastPage {
            get {
                return ResourceManager.GetString("Tooltip_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz plik PDF do anonimizacji..
        /// </summary>
        internal static string Tooltip_LoadPdf {
            get {
                return ResourceManager.GetString("Tooltip_LoadPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb marker — maluj pociągnięciami..
        /// </summary>
        internal static string Tooltip_Marker {
            get {
                return ResourceManager.GetString("Tooltip_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następna strona..
        /// </summary>
        internal static string Tooltip_NextPage {
            get {
                return ResourceManager.GetString("Tooltip_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz projekt z oznaczeniami do anonimizacji..
        /// </summary>
        internal static string Tooltip_OpenProject {
            get {
                return ResourceManager.GetString("Tooltip_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź numer strony i naciśnij Enter..
        /// </summary>
        internal static string Tooltip_PageNumber {
            get {
                return ResourceManager.GetString("Tooltip_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij pozycję, aby wyświetlić stronę..
        /// </summary>
        internal static string Tooltip_PagesList {
            get {
                return ResourceManager.GetString("Tooltip_PagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj identyfikatory (PESEL, KW, itp.)..
        /// </summary>
        internal static string Tooltip_PersonalData {
            get {
                return ResourceManager.GetString("Tooltip_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż zapisany plik PDF po zakończeniu..
        /// </summary>
        internal static string Tooltip_PreviewAfterSave {
            get {
                return ResourceManager.GetString("Tooltip_PreviewAfterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzednia strona..
        /// </summary>
        internal static string Tooltip_PrevPage {
            get {
                return ResourceManager.GetString("Tooltip_PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz stronę do usunięcia..
        /// </summary>
        internal static string Tooltip_RemovePage {
            get {
                return ResourceManager.GetString("Tooltip_RemovePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zakres stron do usunięcia lub do anulowania usunięcia..
        /// </summary>
        internal static string Tooltip_RemovePageRange {
            get {
                return ResourceManager.GetString("Tooltip_RemovePageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb graficzny — bez bezpośredniej ingerencji w treść..
        /// </summary>
        internal static string Tooltip_SafeMode {
            get {
                return ResourceManager.GetString("Tooltip_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zanonimizowany plik PDF pod wybraną nazwą..
        /// </summary>
        internal static string Tooltip_SavePdf {
            get {
                return ResourceManager.GetString("Tooltip_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz projekt z oznaczeniami pod wcześniejszą nazwą..
        /// </summary>
        internal static string Tooltip_SaveProject {
            get {
                return ResourceManager.GetString("Tooltip_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz projekt z oznaczeniami pod wybraną nazwą..
        /// </summary>
        internal static string Tooltip_SaveProjectAs {
            get {
                return ResourceManager.GetString("Tooltip_SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliknij, aby wyszukać..
        /// </summary>
        internal static string Tooltip_Search {
            get {
                return ResourceManager.GetString("Tooltip_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść wynik wyszukiwania..
        /// </summary>
        internal static string Tooltip_SearchClear {
            get {
                return ResourceManager.GetString("Tooltip_SearchClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznacz wyniki wyszukiwania do anonimizacji.
        ///Ponowne kliknięcie usunie zaznaczenia..
        /// </summary>
        internal static string Tooltip_SearchToSelection {
            get {
                return ResourceManager.GetString("Tooltip_SearchToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwsza strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionFirst {
            get {
                return ResourceManager.GetString("Tooltip_SelectionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionLast {
            get {
                return ResourceManager.GetString("Tooltip_SelectionLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następna strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionNext {
            get {
                return ResourceManager.GetString("Tooltip_SelectionNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzednia strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionPrev {
            get {
                return ResourceManager.GetString("Tooltip_SelectionPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdy zaznaczone — plik PDF zostanie zabezpieczony hasłem..
        /// </summary>
        internal static string Tooltip_SetPassword {
            get {
                return ResourceManager.GetString("Tooltip_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozostaw podpisy kwalifikowane w pliku..
        /// </summary>
        internal static string Tooltip_Signatures_Original {
            get {
                return ResourceManager.GetString("Tooltip_Signatures_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń podpisy kwalifikowane przed zapisaniem..
        /// </summary>
        internal static string Tooltip_Signatures_Remove {
            get {
                return ResourceManager.GetString("Tooltip_Signatures_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj raport podpisów na dodatkowej stronie..
        /// </summary>
        internal static string Tooltip_Signatures_Report {
            get {
                return ResourceManager.GetString("Tooltip_Signatures_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiększ stronę. CTRL + rolka w górę..
        /// </summary>
        internal static string Tooltip_ZoomIn {
            get {
                return ResourceManager.GetString("Tooltip_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiększ do maksimum. CTRL + rolka w górę..
        /// </summary>
        internal static string Tooltip_ZoomMax {
            get {
                return ResourceManager.GetString("Tooltip_ZoomMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmniejsz do minimum. CTRL + rolka w dół..
        /// </summary>
        internal static string Tooltip_ZoomMin {
            get {
                return ResourceManager.GetString("Tooltip_ZoomMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomniejsz stronę. CTRL + rolka w dół..
        /// </summary>
        internal static string Tooltip_ZoomOut {
            get {
                return ResourceManager.GetString("Tooltip_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samouczek nie został odnaleziony w lokalizacji:
        ///{0}.
        /// </summary>
        internal static string Tutorial_NotFound {
            get {
                return ResourceManager.GetString("Tutorial_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można uruchomić samouczka:
        ///{0}.
        /// </summary>
        internal static string Tutorial_OpenError {
            get {
                return ResourceManager.GetString("Tutorial_OpenError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy format pliku tutorial.json..
        /// </summary>
        internal static string Tutorial_InvalidFormat {
            get {
                return ResourceManager.GetString("Tutorial_InvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Samouczek nie zawiera tematów..
        /// </summary>
        internal static string Tutorial_NoItems {
            get {
                return ResourceManager.GetString("Tutorial_NoItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Temat.
        /// </summary>
        internal static string Tutorial_Column_Title {
            get {
                return ResourceManager.GetString("Tutorial_Column_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Tutorial_Column_Description {
            get {
                return ResourceManager.GetString("Tutorial_Column_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe lub brakujące pliki licencji:
        ///{0}
        ///
        ///Aplikacja zostanie zamknięta..
        /// </summary>
        internal static string License_StartupError {
            get {
                return ResourceManager.GetString("License_StartupError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brak pliku config.json: {0}.
        /// </summary>
        internal static string License_ConfigMissing {
            get {
                return ResourceManager.GetString("License_ConfigMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy plik config.json: {0}.
        /// </summary>
        internal static string License_ConfigInvalid {
            get {
                return ResourceManager.GetString("License_ConfigInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brak pliku licencji: {0}.
        /// </summary>
        internal static string License_FileMissing {
            get {
                return ResourceManager.GetString("License_FileMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brak pliku klucza publicznego: {0}.
        /// </summary>
        internal static string License_PublicKeyMissing {
            get {
                return ResourceManager.GetString("License_PublicKeyMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa licencja: {0}.
        /// </summary>
        internal static string License_Invalid {
            get {
                return ResourceManager.GetString("License_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Licencja została cofnięta. Aplikacja przechodzi w tryb DEMO..
        /// </summary>
        internal static string License_RevokedDefault {
            get {
                return ResourceManager.GetString("License_RevokedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz PDF.
        /// </summary>
        internal static string UI_Button_OpenPdf {
            get {
                return ResourceManager.GetString("UI_Button_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz projekt.
        /// </summary>
        internal static string UI_Button_OpenProject {
            get {
                return ResourceManager.GetString("UI_Button_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikatory.
        /// </summary>
        internal static string UI_Button_PersonalData {
            get {
                return ResourceManager.GetString("UI_Button_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz PDF.
        /// </summary>
        internal static string UI_Button_SavePdf {
            get {
                return ResourceManager.GetString("UI_Button_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz projekt.
        /// </summary>
        internal static string UI_Button_SaveProject {
            get {
                return ResourceManager.GetString("UI_Button_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz projekt jako.
        /// </summary>
        internal static string UI_Button_SaveProjectAs {
            get {
                return ResourceManager.GetString("UI_Button_SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyróżnienie kolorem.
        /// </summary>
        internal static string UI_Check_HighlightColor {
            get {
                return ResourceManager.GetString("UI_Check_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd po zapisaniu.
        /// </summary>
        internal static string UI_Check_PreviewAfterSave {
            get {
                return ResourceManager.GetString("UI_Check_PreviewAfterSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb graficzny.
        /// </summary>
        internal static string UI_Check_SafeMode {
            get {
                return ResourceManager.GetString("UI_Check_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienie hasła.
        /// </summary>
        internal static string UI_Check_SetPassword {
            get {
                return ResourceManager.GetString("UI_Check_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść wszystko.
        /// </summary>
        internal static string UI_ClearAll {
            get {
                return ResourceManager.GetString("UI_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść stronę.
        /// </summary>
        internal static string UI_ClearPage {
            get {
                return ResourceManager.GetString("UI_ClearPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie kategorie.
        /// </summary>
        internal static string UI_Filter_AllCategories {
            get {
                return ResourceManager.GetString("UI_Filter_AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie strony.
        /// </summary>
        internal static string UI_Filter_AllPages {
            get {
                return ResourceManager.GetString("UI_Filter_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napisy.
        /// </summary>
        internal static string UI_Filter_Annotations {
            get {
                return ResourceManager.GetString("UI_Filter_Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięcia.
        /// </summary>
        internal static string UI_Filter_Deletions {
            get {
                return ResourceManager.GetString("UI_Filter_Deletions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrócenia.
        /// </summary>
        internal static string UI_Filter_Rotations {
            get {
                return ResourceManager.GetString("UI_Filter_Rotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukania.
        /// </summary>
        internal static string UI_Filter_Searches {
            get {
                return ResourceManager.GetString("UI_Filter_Searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznaczenia.
        /// </summary>
        internal static string UI_Filter_Selections {
            get {
                return ResourceManager.GetString("UI_Filter_Selections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr.
        /// </summary>
        internal static string UI_Group_Filter {
            get {
                return ResourceManager.GetString("UI_Group_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strony.
        /// </summary>
        internal static string UI_Group_Pages {
            get {
                return ResourceManager.GetString("UI_Group_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strony do usunięcia.
        /// </summary>
        internal static string UI_Group_PagesToRemove {
            get {
                return ResourceManager.GetString("UI_Group_PagesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie.
        /// </summary>
        internal static string UI_Group_Search {
            get {
                return ResourceManager.GetString("UI_Group_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznaczenia.
        /// </summary>
        internal static string UI_Group_Selections {
            get {
                return ResourceManager.GetString("UI_Group_Selections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpisy.
        /// </summary>
        internal static string UI_Group_Signatures {
            get {
                return ResourceManager.GetString("UI_Group_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona {0}.
        /// </summary>
        internal static string UI_PageLabelFormat {
            get {
                return ResourceManager.GetString("UI_PageLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oryginalne.
        /// </summary>
        internal static string UI_Radio_Signatures_Original {
            get {
                return ResourceManager.GetString("UI_Radio_Signatures_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięte.
        /// </summary>
        internal static string UI_Radio_Signatures_Remove {
            get {
                return ResourceManager.GetString("UI_Radio_Signatures_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport.
        /// </summary>
        internal static string UI_Radio_Signatures_Report {
            get {
                return ResourceManager.GetString("UI_Radio_Signatures_Report", resourceCulture);
            }
        }
    }
}
