//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnonPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copyright © 2025–2026 Urząd Miasta Szczecin; Modyfikacje © 2026 MISART.
        /// </summary>
        internal static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aplikacja dedykowana do anonimizacji plików PDF.
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa aplikacji: {0}
        ///Wersja: {1}
        ///Firma: {2}
        ///{3}
        ///
        ///Opis: {4}
        ///
        ///Licencje i komponenty:
        ///- iText 9 (AGPL-3.0)
        ///- PDFiumSharp / PDFium
        ///- Newtonsoft.Json (MIT)
        ///- BouncyCastle (MIT)
        ///- TesseractOCR (.NET) (Apache-2.0)
        ///
        ///Kod źródłowy dostępny zgodnie z AGPL-3.0 (zobacz plik LICENSE).
        ///Prawa autorskie: zobacz NOTICE.md.
        ///Repozytorium: https://github.com/misart/AnonPDFPro.
        /// </summary>
        internal static string About_Message {
            get {
                return ResourceManager.GetString("About_Message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj chociaż jeden numer strony lub krok podziału!.
        /// </summary>
        internal static string Delete_Err_NoData {
            get {
                return ResourceManager.GetString("Delete_Err_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona początkowa nie może być większa od końcowej..
        /// </summary>
        internal static string Delete_Err_StartGreater {
            get {
                return ResourceManager.GetString("Delete_Err_StartGreater", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona końcowa:.
        /// </summary>
        internal static string Delete_Label_End {
            get {
                return ResourceManager.GetString("Delete_Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona początkowa:.
        /// </summary>
        internal static string Delete_Label_Start {
            get {
                return ResourceManager.GetString("Delete_Label_Start", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Krok:.
        /// </summary>
        internal static string Delete_Label_Step {
            get {
                return ResourceManager.GetString("Delete_Label_Step", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz do usunięcia.
        /// </summary>
        internal static string Delete_Radio_Apply {
            get {
                return ResourceManager.GetString("Delete_Radio_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj wybór.
        /// </summary>
        internal static string Delete_Radio_Cancel {
            get {
                return ResourceManager.GetString("Delete_Radio_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz zakres stron.
        /// </summary>
        internal static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WERSJA DEMONSTRACYJNA ANONPDF PRO.
        /// </summary>
        internal static string Demo_Watermark_Text {
            get {
                return ResourceManager.GetString("Demo_Watermark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pliki APP (*.app)|*.app|Starsze projekty (*.pap)|*.pap.
        /// </summary>
        internal static string Dialog_Filter_PAP {
            get {
                return ResourceManager.GetString("Dialog_Filter_PAP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pliki PDF (*.pdf)|*.pdf.
        /// </summary>
        internal static string Dialog_Filter_PDF {
            get {
                return ResourceManager.GetString("Dialog_Filter_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz plik projektu {0}.
        /// </summary>
        internal static string Dialog_Title_OpenPap {
            get {
                return ResourceManager.GetString("Dialog_Title_OpenPap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz plik PDF.
        /// </summary>
        internal static string Dialog_Title_OpenPdf {
            get {
                return ResourceManager.GetString("Dialog_Title_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj nazwę pliku projektu {0}.
        /// </summary>
        internal static string Dialog_Title_SavePap {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz plik PDF pod inną nazwą niż bieżąca.
        /// </summary>
        internal static string Dialog_Title_SavePdfAs {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePdfAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Środek.
        /// </summary>
        internal static string EditText_AlignCenter {
            get {
                return ResourceManager.GetString("EditText_AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lewo.
        /// </summary>
        internal static string EditText_AlignLeft {
            get {
                return ResourceManager.GetString("EditText_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prawo.
        /// </summary>
        internal static string EditText_AlignRight {
            get {
                return ResourceManager.GetString("EditText_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz kolor.
        /// </summary>
        internal static string EditText_ButtonColor {
            get {
                return ResourceManager.GetString("EditText_ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz czcionkę.
        /// </summary>
        internal static string EditText_ButtonFont {
            get {
                return ResourceManager.GetString("EditText_ButtonFont", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadź jakiś tekst..
        /// </summary>
        internal static string EditText_EmptyError {
            get {
                return ResourceManager.GetString("EditText_EmptyError", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Podmień obraz.
        /// </summary>
        internal static string EditRaster_ButtonReplaceImage {
            get {
                return ResourceManager.GetString("EditRaster_ButtonReplaceImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Reset proporcji.
        /// </summary>
        internal static string EditRaster_ButtonResetAspect {
            get {
                return ResourceManager.GetString("EditRaster_ButtonResetAspect", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Zablokuj obiekt.
        /// </summary>
        internal static string EditRaster_CheckLocked {
            get {
                return ResourceManager.GetString("EditRaster_CheckLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Zachowaj proporcje.
        /// </summary>
        internal static string EditRaster_CheckLockAspect {
            get {
                return ResourceManager.GetString("EditRaster_CheckLockAspect", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Położenie i rozmiar.
        /// </summary>
        internal static string EditRaster_GroupGeometry {
            get {
                return ResourceManager.GetString("EditRaster_GroupGeometry", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Opcje.
        /// </summary>
        internal static string EditRaster_GroupOptions {
            get {
                return ResourceManager.GetString("EditRaster_GroupOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Obrót.
        /// </summary>
        internal static string EditRaster_GroupRotation {
            get {
                return ResourceManager.GetString("EditRaster_GroupRotation", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Źródło obrazu.
        /// </summary>
        internal static string EditRaster_GroupSource {
            get {
                return ResourceManager.GetString("EditRaster_GroupSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Wys.:.
        /// </summary>
        internal static string EditRaster_LabelHeight {
            get {
                return ResourceManager.GetString("EditRaster_LabelHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Przezroczystość (%):.
        /// </summary>
        internal static string EditRaster_LabelOpacity {
            get {
                return ResourceManager.GetString("EditRaster_LabelOpacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Schowek.
        /// </summary>
        internal static string EditRaster_LabelSourceClipboard {
            get {
                return ResourceManager.GetString("EditRaster_LabelSourceClipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Plik.
        /// </summary>
        internal static string EditRaster_LabelSourceFile {
            get {
                return ResourceManager.GetString("EditRaster_LabelSourceFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Nieznane.
        /// </summary>
        internal static string EditRaster_LabelSourceUnknown {
            get {
                return ResourceManager.GetString("EditRaster_LabelSourceUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Szer.:.
        /// </summary>
        internal static string EditRaster_LabelWidth {
            get {
                return ResourceManager.GetString("EditRaster_LabelWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu X:.
        /// </summary>
        internal static string EditRaster_LabelX {
            get {
                return ResourceManager.GetString("EditRaster_LabelX", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Y:.
        /// </summary>
        internal static string EditRaster_LabelY {
            get {
                return ResourceManager.GetString("EditRaster_LabelY", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Kąt:.
        /// </summary>
        internal static string EditRaster_RotationLabel {
            get {
                return ResourceManager.GetString("EditRaster_RotationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj obiekt rastra.
        /// </summary>
        internal static string EditRaster_Title {
            get {
                return ResourceManager.GetString("EditRaster_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyrównanie.
        /// </summary>
        internal static string EditText_GroupAlignment {
            get {
                return ResourceManager.GetString("EditText_GroupAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obrót.
        /// </summary>
        internal static string EditText_GroupRotation {
            get {
                return ResourceManager.GetString("EditText_GroupRotation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Znaczki.
        /// </summary>
        internal static string EditText_GroupSymbols {
            get {
                return ResourceManager.GetString("EditText_GroupSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadź tekst:.
        /// </summary>
        internal static string EditText_LabelText {
            get {
                return ResourceManager.GetString("EditText_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kąt (°):.
        /// </summary>
        internal static string EditText_RotationLabel {
            get {
                return ResourceManager.GetString("EditText_RotationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj napis.
        /// </summary>
        internal static string EditText_Title {
            get {
                return ResourceManager.GetString("EditText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można zapisać — wszystkie strony oznaczone do usunięcia..
        /// </summary>
        internal static string Err_AllPagesMarked {
            get {
                return ResourceManager.GetString("Err_AllPagesMarked", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tego pliku PDF nie można zanonimizować!.
        /// </summary>
        internal static string Err_CannotAnonymizePdf {
            get {
                return ResourceManager.GetString("Err_CannotAnonymizePdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaznaczenie poza bitmapą lub zerowe: {0}.
        /// </summary>
        internal static string Err_Crop_OutsideBitmap {
            get {
                return ResourceManager.GetString("Err_Crop_OutsideBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niepoprawne hasło – spróbuj ponownie..
        /// </summary>
        internal static string Err_IncorrectPassword {
            get {
                return ResourceManager.GetString("Err_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj poprawny numer strony..
        /// </summary>
        internal static string Err_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Err_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowy numer strony: &apos;{0}&apos;..
        /// </summary>
        internal static string Err_InvalidPageNumberValue {
            get {
                return ResourceManager.GetString("Err_InvalidPageNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ten plik PDF jest nieprawidłowy.
        ///
        ///Sprawdź czy możesz go otworzyć w innej aplikacji..
        /// </summary>
        internal static string Err_InvalidPdfFile {
            get {
                return ResourceManager.GetString("Err_InvalidPdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ten format projektu jest nieprawidłowy.
        ///
        ///Skontaktuj się z autorem aplikacji..
        /// </summary>
        internal static string Err_InvalidProjectFormat {
            get {
                return ResourceManager.GetString("Err_InvalidProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas wczytywania ostatnich plików: {0}.
        /// </summary>
        internal static string Err_LoadRecentFiles {
            get {
                return ResourceManager.GetString("Err_LoadRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak skojarzonej aplikacji PDF: {0}.
        /// </summary>
        internal static string Err_NoAssociatedPdfApp {
            get {
                return ResourceManager.GetString("Err_NoAssociatedPdfApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd OCR: {0}.
        /// </summary>
        internal static string Err_OCR {
            get {
                return ResourceManager.GetString("Err_OCR", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można zapisać pliku PDF. Plik wyjściowy jest obecnie używany..
        /// </summary>
        internal static string Err_OutputInUse {
            get {
                return ResourceManager.GetString("Err_OutputInUse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd podczas zapisywania: {0}.
        /// </summary>
        internal static string Err_Save {
            get {
                return ResourceManager.GetString("Err_Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz właściwy plik projektu..
        /// </summary>
        internal static string Err_SelectValidProjectFile {
            get {
                return ResourceManager.GetString("Err_SelectValidProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zbyt mała liczba stron w dokumencie!.
        /// </summary>
        internal static string Err_TooFewPages {
            get {
                return ResourceManager.GetString("Err_TooFewPages", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił nieobsłużony błąd aplikacji:
        ///
        ///{0}
        ///
        ///Szczegóły zapisano w:
        ///{1}.
        /// </summary>
        internal static string Err_UnhandledException {
            get {
                return ResourceManager.GetString("Err_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowy plik config.json: {0}.
        /// </summary>
        internal static string License_ConfigInvalid {
            get {
                return ResourceManager.GetString("License_ConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak pliku config.json: {0}.
        /// </summary>
        internal static string License_ConfigMissing {
            get {
                return ResourceManager.GetString("License_ConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak pliku licencji: {0}.
        /// </summary>
        internal static string License_FileMissing {
            get {
                return ResourceManager.GetString("License_FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowa licencja: {0}.
        /// </summary>
        internal static string License_Invalid {
            get {
                return ResourceManager.GetString("License_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak pliku klucza publicznego: {0}.
        /// </summary>
        internal static string License_PublicKeyMissing {
            get {
                return ResourceManager.GetString("License_PublicKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Licencja została cofnięta. Aplikacja przechodzi w tryb DEMO..
        /// </summary>
        internal static string License_RevokedDefault {
            get {
                return ResourceManager.GetString("License_RevokedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowe lub brakujące pliki licencji:
        ///{0}
        ///
        ///Aplikacja zostanie zamknięta..
        /// </summary>
        internal static string License_StartupError {
            get {
                return ResourceManager.GetString("License_StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj napis.
        /// </summary>
        internal static string Menu_AddText {
            get {
                return ResourceManager.GetString("Menu_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamknij dokument.
        /// </summary>
        internal static string Menu_CloseDocument {
            get {
                return ResourceManager.GetString("Menu_CloseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kopiuj do schowka.
        /// </summary>
        internal static string Menu_CopyToClipboard {
            get {
                return ResourceManager.GetString("Menu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń stronę.
        /// </summary>
        internal static string Menu_DeletePage {
            get {
                return ResourceManager.GetString("Menu_DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Koniec.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Eksport obiektów graficznych.
        /// </summary>
        internal static string Menu_ExportGraphics {
            get {
                return ResourceManager.GetString("Menu_ExportGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &amp;Plik.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu P&amp;omoc.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O aplikacji.
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tryb diagnostyczny.
        /// </summary>
        internal static string Menu_Help_DiagnosticMode {
            get {
                return ResourceManager.GetString("Menu_Help_DiagnosticMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Instrukcja.
        /// </summary>
        internal static string Menu_Help_Help {
            get {
                return ResourceManager.GetString("Menu_Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pokaż licencję.
        /// </summary>
        internal static string Menu_Help_ShowLicense {
            get {
                return ResourceManager.GetString("Menu_Help_ShowLicense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Komponenty osób trzecich.
        /// </summary>
        internal static string Menu_Help_ThirdParty {
            get {
                return ResourceManager.GetString("Menu_Help_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Samouczek.
        /// </summary>
        internal static string Menu_Help_Tutorial {
            get {
                return ResourceManager.GetString("Menu_Help_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomijaj ograniczenia PDF.
        /// </summary>
        internal static string Menu_IgnorePdfRestrictions {
            get {
                return ResourceManager.GetString("Menu_IgnorePdfRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozwala przetwarzać pliki PDF z ograniczeniami edycji ustawionymi przez właściciela..
        /// </summary>
        internal static string Menu_IgnorePdfRestrictions_Tooltip {
            get {
                return ResourceManager.GetString("Menu_IgnorePdfRestrictions_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Język.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Angielski.
        /// </summary>
        internal static string Menu_Language_English {
            get {
                return ResourceManager.GetString("Menu_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polski.
        /// </summary>
        internal static string Menu_Language_Polish {
            get {
                return ResourceManager.GetString("Menu_Language_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Użyj języka systemu.
        /// </summary>
        internal static string Menu_Language_System {
            get {
                return ResourceManager.GetString("Menu_Language_System", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Scal pliki PDF.
        /// </summary>
        internal static string Menu_MergePdf {
            get {
                return ResourceManager.GetString("Menu_MergePdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz ostatni PDF i projekt.
        /// </summary>
        internal static string Menu_OpenLast {
            get {
                return ResourceManager.GetString("Menu_OpenLast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz PDF.
        /// </summary>
        internal static string Menu_OpenPdf {
            get {
                return ResourceManager.GetString("Menu_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz projekt.
        /// </summary>
        internal static string Menu_OpenProject {
            get {
                return ResourceManager.GetString("Menu_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Op&amp;cje.
        /// </summary>
        internal static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pełny ekran.
        /// </summary>
        internal static string Menu_Options_FullScreen {
            get {
                return ResourceManager.GetString("Menu_Options_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Motyw interfejsu.
        /// </summary>
        internal static string Menu_Options_Theme {
            get {
                return ResourceManager.GetString("Menu_Options_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostatnio otwierane pliki.
        /// </summary>
        internal static string Menu_RecentFiles {
            get {
                return ResourceManager.GetString("Menu_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak.
        /// </summary>
        internal static string Menu_RecentFiles_Empty {
            get {
                return ResourceManager.GetString("Menu_RecentFiles_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obróć stronę.
        /// </summary>
        internal static string Menu_RotatePage {
            get {
                return ResourceManager.GetString("Menu_RotatePage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz PDF.
        /// </summary>
        internal static string Menu_SavePdf {
            get {
                return ResourceManager.GetString("Menu_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz projekt.
        /// </summary>
        internal static string Menu_SaveProject {
            get {
                return ResourceManager.GetString("Menu_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz projekt jako.
        /// </summary>
        internal static string Menu_SaveProjectAs {
            get {
                return ResourceManager.GetString("Menu_SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz podpisy do usunięcia.
        /// </summary>
        internal static string Menu_SelectSignaturesToRemove {
            get {
                return ResourceManager.GetString("Menu_SelectSignaturesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podziel plik PDF.
        /// </summary>
        internal static string Menu_SplitPdf {
            get {
                return ResourceManager.GetString("Menu_SplitPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj katalog....
        /// </summary>
        internal static string Merge_AddDirectory {
            get {
                return ResourceManager.GetString("Merge_AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj pliki....
        /// </summary>
        internal static string Merge_AddFiles {
            get {
                return ResourceManager.GetString("Merge_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        internal static string Merge_Cancel {
            get {
                return ResourceManager.GetString("Merge_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyczyść listę.
        /// </summary>
        internal static string Merge_ClearList {
            get {
                return ResourceManager.GetString("Merge_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu W dół.
        /// </summary>
        internal static string Merge_Down {
            get {
                return ResourceManager.GetString("Merge_Down", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd podczas scalania: {0}.
        /// </summary>
        internal static string Merge_Err_Merge {
            get {
                return ResourceManager.GetString("Merge_Err_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        /// </summary>
        internal static string Merge_OK {
            get {
                return ResourceManager.GetString("Merge_OK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń zaznaczone.
        /// </summary>
        internal static string Merge_RemoveSelected {
            get {
                return ResourceManager.GetString("Merge_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pliki zostały pomyślnie scalone..
        /// </summary>
        internal static string Merge_Success {
            get {
                return ResourceManager.GetString("Merge_Success", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Scalanie plików PDF.
        /// </summary>
        internal static string Merge_Title {
            get {
                return ResourceManager.GetString("Merge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu W górę.
        /// </summary>
        internal static string Merge_Up {
            get {
                return ResourceManager.GetString("Merge_Up", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można załadować ostatnio używanych plików..
        /// </summary>
        internal static string Msg_CannotLoadRecentFiles {
            get {
                return ResourceManager.GetString("Msg_CannotLoadRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Masz zdefiniowane zaznaczenia w treści
        ///
        ///.
        /// </summary>
        internal static string Msg_Closing_UnsavedSelectionsPrefix {
            get {
                return ResourceManager.GetString("Msg_Closing_UnsavedSelectionsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć wszystkie zaznaczenia z dokumentu?.
        /// </summary>
        internal static string Msg_Confirm_ClearAllSelections {
            get {
                return ResourceManager.GetString("Msg_Confirm_ClearAllSelections", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz zamknąć aplikację?.
        /// </summary>
        internal static string Msg_Confirm_CloseApp {
            get {
                return ResourceManager.GetString("Msg_Confirm_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz zamknąć dokument?
        ///
        ///Masz zdefiniowane i nie zapisane zaznaczenia w treści....
        /// </summary>
        internal static string Msg_Confirm_CloseWithUnsavedSelections {
            get {
                return ResourceManager.GetString("Msg_Confirm_CloseWithUnsavedSelections", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć ten napis?.
        /// </summary>
        internal static string Msg_Confirm_DeleteTextAnnotation {
            get {
                return ResourceManager.GetString("Msg_Confirm_DeleteTextAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Masz niezapisane zmiany redakcyjne w dokumencie.
        ///
        ///Czy na pewno chcesz je utracić?.
        /// </summary>
        internal static string Msg_Confirm_DiscardUnsavedRedactions {
            get {
                return ResourceManager.GetString("Msg_Confirm_DiscardUnsavedRedactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uwaga, opcja wyszukiwania nazwisk w treści może być czasochłonna
        ///
        ///oraz może nie zwracać poprawnych wyników.
        ///
        ///Czy chcesz kontynuować?.
        /// </summary>
        internal static string Msg_Confirm_NameSearchSlow {
            get {
                return ResourceManager.GetString("Msg_Confirm_NameSearchSlow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz otworzyć nowy plik PDF?
        ///
        ///Masz zdefiniowane i nie zapisane zaznaczenia w treści....
        /// </summary>
        internal static string Msg_Confirm_OpenNewWithUnsavedSelections {
            get {
                return ResourceManager.GetString("Msg_Confirm_OpenNewWithUnsavedSelections", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jest to nieobsługiwany typ pliku. Przeciągnij plik PDF lub plik .app..
        /// </summary>
        internal static string Msg_DragDrop_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Msg_DragDrop_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Eksport obiektów graficznych zakończony.
        ///
        ///Pliki zapisano w katalogu:
        ///{0}.
        /// </summary>
        internal static string Msg_ExportGraphics_Done {
            get {
                return ResourceManager.GetString("Msg_ExportGraphics_Done", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista plików jest pusta..
        /// </summary>
        internal static string Msg_FileListEmpty {
            get {
                return ResourceManager.GetString("Msg_FileListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem z otwarciem pliku: {0}.
        /// </summary>
        internal static string Msg_FileOpenError {
            get {
                return ResourceManager.GetString("Msg_FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik pomocy PDF nie został znaleziony w folderze aplikacji..
        /// </summary>
        internal static string Msg_HelpNotFound {
            get {
                return ResourceManager.GetString("Msg_HelpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik licencji &quot;LICENSE&quot; nie został znaleziony w folderze aplikacji..
        /// </summary>
        internal static string Msg_LicenseNotFound {
            get {
                return ResourceManager.GetString("Msg_LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Załadowano:
        ///PDF: {0}.
        /// </summary>
        internal static string Msg_LoadedPdf {
            get {
                return ResourceManager.GetString("Msg_LoadedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///Projekt: {0}.
        /// </summary>
        internal static string Msg_LoadedProjectLine {
            get {
                return ResourceManager.GetString("Msg_LoadedProjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyłączenie za {0}.
        /// </summary>
        internal static string Msg_MaintenanceCountdown {
            get {
                return ResourceManager.GetString("Msg_MaintenanceCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aplikacja została zamknięta z przyczyn serwisowych. Czy chcesz przywrócić ostatnią sesję?.
        /// </summary>
        internal static string Msg_MaintenanceRecoveryPrompt {
            get {
                return ResourceManager.GetString("Msg_MaintenanceRecoveryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usługa umożliwiająca wyszukiwanie nazwisk jest obecnie niedostępna..
        /// </summary>
        internal static string Msg_NameSearchServiceUnavailable {
            get {
                return ResourceManager.GetString("Msg_NameSearchServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dostępna jest do pobrania nowsza wersja {0} (data aktualizacji: {1})..
        /// </summary>
        internal static string Msg_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Msg_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiany w tej wersji:.
        /// </summary>
        internal static string Msg_NewVersionChangesHeader {
            get {
                return ResourceManager.GetString("Msg_NewVersionChangesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wykryto nowszą wersję aplikacji {1}. Do {0} będzie przeprowadzana aktualizacja aplikacji.
        ///
        ///Proszę zapisać wyniki swojej pracy i wyłączyć program.
        ///
        ///  Automatyczne wyłączenie nastąpi za 5 minut..
        /// </summary>
        internal static string Msg_NewVersionDetectedMaintenance {
            get {
                return ResourceManager.GetString("Msg_NewVersionDetectedMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Link do pobrania: {0}.
        /// </summary>
        internal static string Msg_NewVersionDownload {
            get {
                return ResourceManager.GetString("Msg_NewVersionDownload", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak listy zmian..
        /// </summary>
        internal static string Msg_NewVersionNoChanges {
            get {
                return ResourceManager.GetString("Msg_NewVersionNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu W dokumencie nie znaleziono poprawnych numerów PESEL, KW i innych identyfikatorów..
        /// </summary>
        internal static string Msg_NoIdentifiersFound {
            get {
                return ResourceManager.GetString("Msg_NoIdentifiersFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie podano hasła – otwarcie anulowane..
        /// </summary>
        internal static string Msg_NoPasswordOpenCancelled {
            get {
                return ResourceManager.GetString("Msg_NoPasswordOpenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Na bieżącej stronie nie znaleziono wyników wyszukiwania..
        /// </summary>
        internal static string Msg_NoSearchResultsOnPage {
            get {
                return ResourceManager.GetString("Msg_NoSearchResultsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak zaznaczeń na bieżącej stronie..
        /// </summary>
        internal static string Msg_NoSelectionsOnPage {
            get {
                return ResourceManager.GetString("Msg_NoSelectionsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się pobrać tekstu z żadnego zaznaczenia..
        /// </summary>
        internal static string Msg_NoTextFromSelections {
            get {
                return ResourceManager.GetString("Msg_NoTextFromSelections", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik z informacjami o komponentach &quot;THIRD-PARTY-NOTICES.md&quot; nie został znaleziony w folderze aplikacji..
        /// </summary>
        internal static string Msg_NoticesNotFound {
            get {
                return ResourceManager.GetString("Msg_NoticesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił problem z otwarciem pliku PDF: {0}.
        /// </summary>
        internal static string Msg_OpenPdfError {
            get {
                return ResourceManager.GetString("Msg_OpenPdfError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz najpierw plik PDF..
        /// </summary>
        internal static string Msg_OpenPdfFirst {
            get {
                return ResourceManager.GetString("Msg_OpenPdfFirst", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprawdź zapisany dokument PDF na podglądzie..
        /// </summary>
        internal static string Msg_PreviewSavedPdf {
            get {
                return ResourceManager.GetString("Msg_PreviewSavedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisano bieżący stan prac nad projektem
        ///pod wybraną nazwą..
        /// </summary>
        internal static string Msg_ProjectSaved {
            get {
                return ResourceManager.GetString("Msg_ProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono &quot;{0}&quot;..
        /// </summary>
        internal static string Msg_SearchNotFound {
            get {
                return ResourceManager.GetString("Msg_SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktualnie do {0} jest przeprowadzana aktualizacja aplikacji {1}..
        /// </summary>
        internal static string Msg_ServiceUpdateInProgress {
            get {
                return ResourceManager.GetString("Msg_ServiceUpdateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} możliwość zmiany pozycji tekstu..
        /// </summary>
        internal static string Msg_TextPositionInfo {
            get {
                return ResourceManager.GetString("Msg_TextPositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Teksty z zaznaczeń zostały skopiowane do schowka..
        /// </summary>
        internal static string Msg_TextsCopiedToClipboard {
            get {
                return ResourceManager.GetString("Msg_TextsCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zainstalowana wersja przekracza zakres wykupionego wsparcia. Licencja na nowsze wersje nie została wykupiona.
        ///
        ///Aplikacja przechodzi w tryb DEMO..
        /// </summary>
        internal static string Msg_UpdateLicenseOutOfRange {
            get {
                return ResourceManager.GetString("Msg_UpdateLicenseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło:.
        /// </summary>
        internal static string PwdPrompt_Label_Password {
            get {
                return ResourceManager.GetString("PwdPrompt_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Możesz zmienić lub usunąć hasło PDF.
        /// </summary>
        internal static string PwdPrompt_Title_CanChangeRemove {
            get {
                return ResourceManager.GetString("PwdPrompt_Title_CanChangeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj hasło PDF.
        /// </summary>
        internal static string PwdPrompt_Title_Enter {
            get {
                return ResourceManager.GetString("PwdPrompt_Title_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data.
        /// </summary>
        internal static string Signatures_Report_Field_SignDate {
            get {
                return ResourceManager.GetString("Signatures_Report_Field_SignDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sygnatariusz.
        /// </summary>
        internal static string Signatures_Report_Field_SignerName {
            get {
                return ResourceManager.GetString("Signatures_Report_Field_SignerName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tytuł.
        /// </summary>
        internal static string Signatures_Report_Field_SignerTitle {
            get {
                return ResourceManager.GetString("Signatures_Report_Field_SignerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista podpisów kwalifikowanych w oryginalnym dokumencie (przed anonimizacją):.
        /// </summary>
        internal static string Signatures_Report_Title {
            get {
                return ResourceManager.GetString("Signatures_Report_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data.
        /// </summary>
        internal static string Signatures_Select_Column_Date {
            get {
                return ResourceManager.GetString("Signatures_Select_Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podpisujący.
        /// </summary>
        internal static string Signatures_Select_Column_Name {
            get {
                return ResourceManager.GetString("Signatures_Select_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stanowisko.
        /// </summary>
        internal static string Signatures_Select_Column_Title {
            get {
                return ResourceManager.GetString("Signatures_Select_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz podpisy do usunięcia.
        /// </summary>
        internal static string Signatures_Select_Title {
            get {
                return ResourceManager.GetString("Signatures_Select_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przeglądaj....
        /// </summary>
        internal static string Split_Browse {
            get {
                return ResourceManager.GetString("Split_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz plik PDF.
        /// </summary>
        internal static string Split_Dlg_Title {
            get {
                return ResourceManager.GetString("Split_Dlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd przy odczycie pliku PDF:\n{0}.
        /// </summary>
        internal static string Split_Err_ReadFile {
            get {
                return ResourceManager.GetString("Split_Err_ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Proszę wybrać istniejący plik PDF..
        /// </summary>
        internal static string Split_Err_SelectFile {
            get {
                return ResourceManager.GetString("Split_Err_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz plik PDF:.
        /// </summary>
        internal static string Split_FileLabel {
            get {
                return ResourceManager.GetString("Split_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba stron: {0}.
        /// </summary>
        internal static string Split_PageCountLabel {
            get {
                return ResourceManager.GetString("Split_PageCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba stron: ?.
        /// </summary>
        internal static string Split_PageCountUnknown {
            get {
                return ResourceManager.GetString("Split_PageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj numery stron do podziału (oddzielone przecinkami):.
        /// </summary>
        internal static string Split_PagesLabel {
            get {
                return ResourceManager.GetString("Split_PagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj krok podziału:.
        /// </summary>
        internal static string Split_StepLabel {
            get {
                return ResourceManager.GetString("Split_StepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dokument PDF został podzielony..
        /// </summary>
        internal static string Split_Success {
            get {
                return ResourceManager.GetString("Split_Success", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podział dokumentu PDF.
        /// </summary>
        internal static string Split_Title {
            get {
                return ResourceManager.GetString("Split_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bałtycka bryza.
        /// </summary>
        internal static string Theme_BalticBreeze {
            get {
                return ResourceManager.GetString("Theme_BalticBreeze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Leśna zieleń.
        /// </summary>
        internal static string Theme_ForestGreen {
            get {
                return ResourceManager.GetString("Theme_ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grafitowa ciemność.
        /// </summary>
        internal static string Theme_GraphiteDark {
            get {
                return ResourceManager.GetString("Theme_GraphiteDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nordycki chłód.
        /// </summary>
        internal static string Theme_NordCoolLight {
            get {
                return ResourceManager.GetString("Theme_NordCoolLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ciemny turkus.
        /// </summary>
        internal static string Theme_OledDarkTeal {
            get {
                return ResourceManager.GetString("Theme_OledDarkTeal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miękkie światło.
        /// </summary>
        internal static string Theme_SoftLight {
            get {
                return ResourceManager.GetString("Theme_SoftLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ciepły piasek.
        /// </summary>
        internal static string Theme_WarmSand {
            get {
                return ResourceManager.GetString("Theme_WarmSand", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdzenie.
        /// </summary>
        internal static string Title_Confirmation {
            get {
                return ResourceManager.GetString("Title_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd krytyczny aplikacji.
        /// </summary>
        internal static string Title_CriticalAppError {
            get {
                return ResourceManager.GetString("Title_CriticalAppError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacja.
        /// </summary>
        internal static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sukces.
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostrzeżenie.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tryb box — zaznacz prostokątem..
        /// </summary>
        internal static string Tooltip_Box {
            get {
                return ResourceManager.GetString("Tooltip_Box", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń wszystkie zaznaczenia z dokumentu..
        /// </summary>
        internal static string Tooltip_ClearAll {
            get {
                return ResourceManager.GetString("Tooltip_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń zaznaczenia z bieżącej strony..
        /// </summary>
        internal static string Tooltip_ClearPage {
            get {
                return ResourceManager.GetString("Tooltip_ClearPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pierwsza strona..
        /// </summary>
        internal static string Tooltip_FirstPage {
            get {
                return ResourceManager.GetString("Tooltip_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu W zapisie zaznaczenia będą wyróżnione kolorem..
        /// </summary>
        internal static string Tooltip_HighlightColor {
            get {
                return ResourceManager.GetString("Tooltip_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostatnia strona..
        /// </summary>
        internal static string Tooltip_LastPage {
            get {
                return ResourceManager.GetString("Tooltip_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz plik PDF do anonimizacji..
        /// </summary>
        internal static string Tooltip_LoadPdf {
            get {
                return ResourceManager.GetString("Tooltip_LoadPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tryb marker — maluj pociągnięciami..
        /// </summary>
        internal static string Tooltip_Marker {
            get {
                return ResourceManager.GetString("Tooltip_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następna strona..
        /// </summary>
        internal static string Tooltip_NextPage {
            get {
                return ResourceManager.GetString("Tooltip_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz projekt z oznaczeniami do anonimizacji..
        /// </summary>
        internal static string Tooltip_OpenProject {
            get {
                return ResourceManager.GetString("Tooltip_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadź numer strony i naciśnij Enter..
        /// </summary>
        internal static string Tooltip_PageNumber {
            get {
                return ResourceManager.GetString("Tooltip_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kliknij pozycję, aby wyświetlić stronę..
        /// </summary>
        internal static string Tooltip_PagesList {
            get {
                return ResourceManager.GetString("Tooltip_PagesList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyszukaj identyfikatory (PESEL, KW, itp.)..
        /// </summary>
        internal static string Tooltip_PersonalData {
            get {
                return ResourceManager.GetString("Tooltip_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pokaż zapisany plik PDF po zakończeniu..
        /// </summary>
        internal static string Tooltip_PreviewAfterSave {
            get {
                return ResourceManager.GetString("Tooltip_PreviewAfterSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poprzednia strona..
        /// </summary>
        internal static string Tooltip_PrevPage {
            get {
                return ResourceManager.GetString("Tooltip_PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaznacz stronę do usunięcia..
        /// </summary>
        internal static string Tooltip_RemovePage {
            get {
                return ResourceManager.GetString("Tooltip_RemovePage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz zakres stron do usunięcia lub do anulowania usunięcia..
        /// </summary>
        internal static string Tooltip_RemovePageRange {
            get {
                return ResourceManager.GetString("Tooltip_RemovePageRange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tryb graficzny — bez bezpośredniej ingerencji w treść..
        /// </summary>
        internal static string Tooltip_SafeMode {
            get {
                return ResourceManager.GetString("Tooltip_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz zanonimizowany plik PDF pod wybraną nazwą..
        /// </summary>
        internal static string Tooltip_SavePdf {
            get {
                return ResourceManager.GetString("Tooltip_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz projekt z oznaczeniami pod wcześniejszą nazwą..
        /// </summary>
        internal static string Tooltip_SaveProject {
            get {
                return ResourceManager.GetString("Tooltip_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz projekt z oznaczeniami pod wybraną nazwą..
        /// </summary>
        internal static string Tooltip_SaveProjectAs {
            get {
                return ResourceManager.GetString("Tooltip_SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kliknij, aby wyszukać..
        /// </summary>
        internal static string Tooltip_Search {
            get {
                return ResourceManager.GetString("Tooltip_Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyczyść wynik wyszukiwania..
        /// </summary>
        internal static string Tooltip_SearchClear {
            get {
                return ResourceManager.GetString("Tooltip_SearchClear", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oznacz wyniki wyszukiwania do anonimizacji.
        ///Ponowne kliknięcie usunie zaznaczenia..
        /// </summary>
        internal static string Tooltip_SearchToSelection {
            get {
                return ResourceManager.GetString("Tooltip_SearchToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pierwsza strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionFirst {
            get {
                return ResourceManager.GetString("Tooltip_SelectionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostatnia strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionLast {
            get {
                return ResourceManager.GetString("Tooltip_SelectionLast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następna strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionNext {
            get {
                return ResourceManager.GetString("Tooltip_SelectionNext", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poprzednia strona z zaznaczeniami..
        /// </summary>
        internal static string Tooltip_SelectionPrev {
            get {
                return ResourceManager.GetString("Tooltip_SelectionPrev", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gdy zaznaczone — plik PDF zostanie zabezpieczony hasłem..
        /// </summary>
        internal static string Tooltip_SetPassword {
            get {
                return ResourceManager.GetString("Tooltip_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anonimizuj podpisy i pozostaw ich oryginalne wizualizacje..
        /// </summary>
        internal static string Tooltip_Signatures_Original {
            get {
                return ResourceManager.GetString("Tooltip_Signatures_Original", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń podpisy kwalifikowane przed zapisaniem..
        /// </summary>
        internal static string Tooltip_Signatures_Remove {
            get {
                return ResourceManager.GetString("Tooltip_Signatures_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wygeneruj raport podpisów na dodatkowej stronie..
        /// </summary>
        internal static string Tooltip_Signatures_Report {
            get {
                return ResourceManager.GetString("Tooltip_Signatures_Report", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiększ stronę. CTRL + rolka w górę..
        /// </summary>
        internal static string Tooltip_ZoomIn {
            get {
                return ResourceManager.GetString("Tooltip_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powiększ do maksimum. CTRL + rolka w górę..
        /// </summary>
        internal static string Tooltip_ZoomMax {
            get {
                return ResourceManager.GetString("Tooltip_ZoomMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmniejsz do minimum. CTRL + rolka w dół..
        /// </summary>
        internal static string Tooltip_ZoomMin {
            get {
                return ResourceManager.GetString("Tooltip_ZoomMin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomniejsz stronę. CTRL + rolka w dół..
        /// </summary>
        internal static string Tooltip_ZoomOut {
            get {
                return ResourceManager.GetString("Tooltip_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opis.
        /// </summary>
        internal static string Tutorial_Column_Description {
            get {
                return ResourceManager.GetString("Tutorial_Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Temat.
        /// </summary>
        internal static string Tutorial_Column_Title {
            get {
                return ResourceManager.GetString("Tutorial_Column_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowy format pliku tutorial.json..
        /// </summary>
        internal static string Tutorial_InvalidFormat {
            get {
                return ResourceManager.GetString("Tutorial_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Samouczek nie zawiera tematów..
        /// </summary>
        internal static string Tutorial_NoItems {
            get {
                return ResourceManager.GetString("Tutorial_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Samouczek nie został odnaleziony w lokalizacji:
        ///{0}.
        /// </summary>
        internal static string Tutorial_NotFound {
            get {
                return ResourceManager.GetString("Tutorial_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można uruchomić samouczka:
        ///{0}.
        /// </summary>
        internal static string Tutorial_OpenError {
            get {
                return ResourceManager.GetString("Tutorial_OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz PDF.
        /// </summary>
        internal static string UI_Button_OpenPdf {
            get {
                return ResourceManager.GetString("UI_Button_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz projekt.
        /// </summary>
        internal static string UI_Button_OpenProject {
            get {
                return ResourceManager.GetString("UI_Button_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Identyfikatory.
        /// </summary>
        internal static string UI_Button_PersonalData {
            get {
                return ResourceManager.GetString("UI_Button_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz PDF.
        /// </summary>
        internal static string UI_Button_SavePdf {
            get {
                return ResourceManager.GetString("UI_Button_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz projekt.
        /// </summary>
        internal static string UI_Button_SaveProject {
            get {
                return ResourceManager.GetString("UI_Button_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz projekt jako.
        /// </summary>
        internal static string UI_Button_SaveProjectAs {
            get {
                return ResourceManager.GetString("UI_Button_SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyróżnienie kolorem.
        /// </summary>
        internal static string UI_Check_HighlightColor {
            get {
                return ResourceManager.GetString("UI_Check_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podgląd po zapisaniu.
        /// </summary>
        internal static string UI_Check_PreviewAfterSave {
            get {
                return ResourceManager.GetString("UI_Check_PreviewAfterSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tryb graficzny.
        /// </summary>
        internal static string UI_Check_SafeMode {
            get {
                return ResourceManager.GetString("UI_Check_SafeMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienie hasła.
        /// </summary>
        internal static string UI_Check_SetPassword {
            get {
                return ResourceManager.GetString("UI_Check_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyczyść wszystko.
        /// </summary>
        internal static string UI_ClearAll {
            get {
                return ResourceManager.GetString("UI_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyczyść stronę.
        /// </summary>
        internal static string UI_ClearPage {
            get {
                return ResourceManager.GetString("UI_ClearPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie kategorie.
        /// </summary>
        internal static string UI_Filter_AllCategories {
            get {
                return ResourceManager.GetString("UI_Filter_AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie strony.
        /// </summary>
        internal static string UI_Filter_AllPages {
            get {
                return ResourceManager.GetString("UI_Filter_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Napisy.
        /// </summary>
        internal static string UI_Filter_Annotations {
            get {
                return ResourceManager.GetString("UI_Filter_Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunięcia.
        /// </summary>
        internal static string UI_Filter_Deletions {
            get {
                return ResourceManager.GetString("UI_Filter_Deletions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obrócenia.
        /// </summary>
        internal static string UI_Filter_Rotations {
            get {
                return ResourceManager.GetString("UI_Filter_Rotations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyszukania.
        /// </summary>
        internal static string UI_Filter_Searches {
            get {
                return ResourceManager.GetString("UI_Filter_Searches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaznaczenia.
        /// </summary>
        internal static string UI_Filter_Selections {
            get {
                return ResourceManager.GetString("UI_Filter_Selections", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Filtr.
        /// </summary>
        internal static string UI_Group_Filter {
            get {
                return ResourceManager.GetString("UI_Group_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwórz.
        /// </summary>
        internal static string UI_Group_Open {
            get {
                return ResourceManager.GetString("UI_Group_Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Opcje.
        /// </summary>
        internal static string UI_Group_Options {
            get {
                return ResourceManager.GetString("UI_Group_Options", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strony.
        /// </summary>
        internal static string UI_Group_Pages {
            get {
                return ResourceManager.GetString("UI_Group_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strony do usunięcia.
        /// </summary>
        internal static string UI_Group_PagesToRemove {
            get {
                return ResourceManager.GetString("UI_Group_PagesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        internal static string UI_Group_Save {
            get {
                return ResourceManager.GetString("UI_Group_Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyszukiwanie.
        /// </summary>
        internal static string UI_Group_Search {
            get {
                return ResourceManager.GetString("UI_Group_Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaznaczenia.
        /// </summary>
        internal static string UI_Group_Selections {
            get {
                return ResourceManager.GetString("UI_Group_Selections", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podpisy.
        /// </summary>
        internal static string UI_Group_Signatures {
            get {
                return ResourceManager.GetString("UI_Group_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strona {0}.
        /// </summary>
        internal static string UI_PageLabelFormat {
            get {
                return ResourceManager.GetString("UI_PageLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oryginalne.
        /// </summary>
        internal static string UI_Radio_Signatures_Original {
            get {
                return ResourceManager.GetString("UI_Radio_Signatures_Original", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunięte.
        /// </summary>
        internal static string UI_Radio_Signatures_Remove {
            get {
                return ResourceManager.GetString("UI_Radio_Signatures_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Raport.
        /// </summary>
        internal static string UI_Radio_Signatures_Report {
            get {
                return ResourceManager.GetString("UI_Radio_Signatures_Report", resourceCulture);
            }
        }
    }
}
