//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonPDF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPdfPath {
            get {
                return ((string)(this["LastPdfPath"]));
            }
            set {
                this["LastPdfPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPapPath {
            get {
                return ((string)(this["LastPapPath"]));
            }
            set {
                this["LastPapPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentFiles {
            get {
                return ((string)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastColorCheckBoxState {
            get {
                return ((bool)(this["LastColorCheckBoxState"]));
            }
            set {
                this["LastColorCheckBoxState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastOutlineCheckBoxState {
            get {
                return ((bool)(this["LastOutlineCheckBoxState"]));
            }
            set {
                this["LastOutlineCheckBoxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LastOpenSavedPDFCheckBoxState {
            get {
                return ((bool)(this["LastOpenSavedPDFCheckBoxState"]));
            }
            set {
                this["LastOpenSavedPDFCheckBoxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LastSignaturesRemoveRadioButton {
            get {
                return ((bool)(this["LastSignaturesRemoveRadioButton"]));
            }
            set {
                this["LastSignaturesRemoveRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastSignaturesOriginalRadioButton {
            get {
                return ((bool)(this["LastSignaturesOriginalRadioButton"]));
            }
            set {
                this["LastSignaturesOriginalRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastSignaturesRaportRadioButton {
            get {
                return ((bool)(this["LastSignaturesRaportRadioButton"]));
            }
            set {
                this["LastSignaturesRaportRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastSafeModeCheckBoxState {
            get {
                return ((bool)(this["LastSafeModeCheckBoxState"]));
            }
            set {
                this["LastSafeModeCheckBoxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TutorialShown {
            get {
                return ((bool)(this["TutorialShown"]));
            }
            set {
                this["TutorialShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnorePdfRestrictions {
            get {
                return ((bool)(this["IgnorePdfRestrictions"]));
            }
            set {
                this["IgnorePdfRestrictions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiagnosticMode {
            get {
                return ((bool)(this["DiagnosticMode"]));
            }
            set {
                this["DiagnosticMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferredUICulture {
            get {
                return ((string)(this["PreferredUICulture"]));
            }
            set {
                this["PreferredUICulture"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BalticBreeze")]
        public string PreferredUiTheme {
            get {
                return ((string)(this["PreferredUiTheme"]));
            }
            set {
                this["PreferredUiTheme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExclusionAuthorityName {
            get {
                return ((string)(this["ExclusionAuthorityName"]));
            }
            set {
                this["ExclusionAuthorityName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExclusionAuthorityVerified {
            get {
                return ((bool)(this["ExclusionAuthorityVerified"]));
            }
            set {
                this["ExclusionAuthorityVerified"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoFootnotesEnabled {
            get {
                return ((bool)(this["AutoFootnotesEnabled"]));
            }
            set {
                this["AutoFootnotesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SnapToGridEnabled {
            get {
                return ((bool)(this["SnapToGridEnabled"]));
            }
            set {
                this["SnapToGridEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddObjectsByPageRotationEnabled {
            get {
                return ((bool)(this["AddObjectsByPageRotationEnabled"]));
            }
            set {
                this["AddObjectsByPageRotationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CombineObjectsWithScanPagesEnabled {
            get {
                return ((bool)(this["CombineObjectsWithScanPagesEnabled"]));
            }
            set {
                this["CombineObjectsWithScanPagesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReducePdfFileSizeEnabled {
            get {
                return ((bool)(this["ReducePdfFileSizeEnabled"]));
            }
            set {
                this["ReducePdfFileSizeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseThumbnailsTabInRightPanel {
            get {
                return ((bool)(this["UseThumbnailsTabInRightPanel"]));
            }
            set {
                this["UseThumbnailsTabInRightPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pages")]
        public string RightPanelSelectedTabKey {
            get {
                return ((string)(this["RightPanelSelectedTabKey"]));
            }
            set {
                this["RightPanelSelectedTabKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218")]
        public int RightPanelWidth {
            get {
                return ((int)(this["RightPanelWidth"]));
            }
            set {
                this["RightPanelWidth"] = value;
            }
        }
    }
}
